title: Jacqueline Wong
email: l.y.jwong@uu.nl
url: "" # the base hostname & protocol for your site, e.g. http://example.com
baseurl: "" # the subpath of your site, e.g. /blog
title: "Jacqueline Wong's Personal Website" # the name of your site, e.g. ACME Corp.
